aws:
    region: '%env(AWS_REGION)%'
    credentials:
        key: '%env(AWS_KEY)%'
        secret: '%env(AWS_SECRET)%'
    DynamoDb:
        region: '%env(AWS_REGION)%'
        version: "latest"
    S3:
        region: '%env(AWS_REGION)%'
        version: "latest"