// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	album "github.com/hyoa/album/api/internal/album"
	mock "github.com/stretchr/testify/mock"
)

// AlbumRepository is an autogenerated mock type for the AlbumRepository type
type AlbumRepository struct {
	mock.Mock
}

// DeleteBySlug provides a mock function with given fields: slug
func (_m *AlbumRepository) DeleteBySlug(slug string) error {
	ret := _m.Called(slug)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields:
func (_m *AlbumRepository) FindAll() ([]album.Album, error) {
	ret := _m.Called()

	var r0 []album.Album
	if rf, ok := ret.Get(0).(func() []album.Album); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]album.Album)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBySlug provides a mock function with given fields: slug
func (_m *AlbumRepository) FindBySlug(slug string) (album.Album, error) {
	ret := _m.Called(slug)

	var r0 album.Album
	if rf, ok := ret.Get(0).(func(string) album.Album); ok {
		r0 = rf(slug)
	} else {
		r0 = ret.Get(0).(album.Album)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: a
func (_m *AlbumRepository) Save(a album.Album) error {
	ret := _m.Called(a)

	var r0 error
	if rf, ok := ret.Get(0).(func(album.Album) error); ok {
		r0 = rf(a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Search provides a mock function with given fields: includePrivate, includeNoMedias, limit, offset, term, order
func (_m *AlbumRepository) Search(includePrivate bool, includeNoMedias bool, limit int, offset int, term string, order string) ([]album.Album, error) {
	ret := _m.Called(includePrivate, includeNoMedias, limit, offset, term, order)

	var r0 []album.Album
	if rf, ok := ret.Get(0).(func(bool, bool, int, int, string, string) []album.Album); ok {
		r0 = rf(includePrivate, includeNoMedias, limit, offset, term, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]album.Album)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(bool, bool, int, int, string, string) error); ok {
		r1 = rf(includePrivate, includeNoMedias, limit, offset, term, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: a
func (_m *AlbumRepository) Update(a album.Album) error {
	ret := _m.Called(a)

	var r0 error
	if rf, ok := ret.Get(0).(func(album.Album) error); ok {
		r0 = rf(a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAlbumRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewAlbumRepository creates a new instance of AlbumRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAlbumRepository(t mockConstructorTestingTNewAlbumRepository) *AlbumRepository {
	mock := &AlbumRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
