// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ErrorWithTranslation is an autogenerated mock type for the ErrorWithTranslation type
type ErrorWithTranslation struct {
	mock.Mock
}

// ID provides a mock function with given fields:
func (_m *ErrorWithTranslation) ID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewErrorWithTranslation interface {
	mock.TestingT
	Cleanup(func())
}

// NewErrorWithTranslation creates a new instance of ErrorWithTranslation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewErrorWithTranslation(t mockConstructorTestingTNewErrorWithTranslation) *ErrorWithTranslation {
	mock := &ErrorWithTranslation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
