// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// S3Interactor is an autogenerated mock type for the S3Interactor type
type S3Interactor struct {
	mock.Mock
}

// GetJsonFile provides a mock function with given fields: fileName
func (_m *S3Interactor) GetJsonFile(fileName string) ([]byte, error) {
	ret := _m.Called(fileName)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(fileName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(fileName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MediaExist provides a mock function with given fields: key, bucket
func (_m *S3Interactor) MediaExist(key string, bucket string) (bool, error) {
	ret := _m.Called(key, bucket)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(key, bucket)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(key, bucket)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignGetUri provides a mock function with given fields: key, bucket
func (_m *S3Interactor) SignGetUri(key string, bucket string) (string, error) {
	ret := _m.Called(key, bucket)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(key, bucket)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(key, bucket)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignPutUri provides a mock function with given fields: key, bucket
func (_m *S3Interactor) SignPutUri(key string, bucket string) (string, error) {
	ret := _m.Called(key, bucket)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(key, bucket)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(key, bucket)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteJsonFile provides a mock function with given fields: fileName, jsonByte
func (_m *S3Interactor) WriteJsonFile(fileName string, jsonByte []byte) error {
	ret := _m.Called(fileName, jsonByte)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(fileName, jsonByte)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewS3Interactor interface {
	mock.TestingT
	Cleanup(func())
}

// NewS3Interactor creates a new instance of S3Interactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewS3Interactor(t mockConstructorTestingTNewS3Interactor) *S3Interactor {
	mock := &S3Interactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
