// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// tokenInput is an autogenerated mock type for the tokenInput type
type tokenInput struct {
	mock.Mock
}

type mockConstructorTestingTnewTokenInput interface {
	mock.TestingT
	Cleanup(func())
}

// newTokenInput creates a new instance of tokenInput. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newTokenInput(t mockConstructorTestingTnewTokenInput) *tokenInput {
	mock := &tokenInput{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
