// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// token is an autogenerated mock type for the token type
type token struct {
	mock.Mock
}

type mockConstructorTestingTnewToken interface {
	mock.TestingT
	Cleanup(func())
}

// newToken creates a new instance of token. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newToken(t mockConstructorTestingTnewToken) *token {
	mock := &token{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
