// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// VideoConverter is an autogenerated mock type for the VideoConverter type
type VideoConverter struct {
	mock.Mock
}

// Convert provides a mock function with given fields: key
func (_m *VideoConverter) Convert(key string) error {
	ret := _m.Called(key)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewVideoConverter interface {
	mock.TestingT
	Cleanup(func())
}

// NewVideoConverter creates a new instance of VideoConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewVideoConverter(t mockConstructorTestingTNewVideoConverter) *VideoConverter {
	mock := &VideoConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
